# Generated by Django 5.2.8 on 2025-11-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[('experience', 'Employee Experience'), ('samrika', 'Samrika'), ('general', 'General')], max_length=50, null=True),
        ),
    ]
