# Generated by Django 5.2.8 on 2026-01-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[('none', 'Select Article Type'), ('experience', 'Employee Experience'), ('smarika', 'Smarika'), ('general', 'General')], max_length=50, null=True),
        ),
    ]
