# Generated by Django 5.2.8 on 2025-11-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[('', 'Select Article Type'), ('experience', 'Employee Experience'), ('samrika', 'Samrika'), ('general', 'General')], max_length=50, null=True),
        ),
    ]
